# Generated by Django 5.2.6 on 2025-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0002_permission_role_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
