# Generated by Django 5.2.6 on 2025-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff_account",
            field=models.BooleanField(default=False),
        ),
    ]
