# Generated by Django 5.1.6 on 2025-09-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0009_customuser_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
