# Generated by Django 5.1.6 on 2025-09-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "00013_alter_cart_cart_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Awaiting Confirmation", "Awaiting Confirmation"),
                    ("Confirmed", "Confirmed"),
                    ("Processing", "Processing"),
                    ("Shipping", "Shipping"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                    ("Disputed", "Disputed"),
                ],
                max_length=32,
            ),
        ),
    ]
