# Generated by Django 5.1.6 on 2025-10-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0014_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Pending from Inventory", "Pending from Inventory"),
                    ("Pending from Delivery", "Pending from Delivery"),
                    ("Shipping", "Shipping"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=32,
            ),
        ),
    ]
