# Generated by Django 5.1.6 on 2025-10-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0015_product_quantity_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="checkout_id",
            new_name="checkout_id",
        ),
    ]
