# Generated by Django 5.1.6 on 2025-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0016_rename_checkout_id_order_stripe_checkout_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('products', models.ManyToManyField(related_name='discounts', to='apiApp.product')),
            ],
        ),
    ]
